const a = /* @__PURE__ */ location.pathname.split("/").slice(0, -1).join("/"), o = [
  a + "/_app/immutable/entry/app.4c18f94e.js",
  a + "/_app/immutable/assets/0.3f057e05.css",
  a + "/_app/immutable/nodes/0.b131c195.js",
  a + "/_app/immutable/nodes/1.351b8641.js",
  a + "/_app/immutable/assets/404.9de340c4.webp",
  a + "/_app/immutable/assets/2.a3ec6066.css",
  a + "/_app/immutable/nodes/2.abff9ee7.js",
  a + "/_app/immutable/nodes/3.388ff96c.js",
  a + "/_app/immutable/nodes/4.69336eb1.js",
  a + "/_app/immutable/nodes/5.5a0ecf22.js",
  a + "/_app/immutable/nodes/6.d6995224.js",
  a + "/_app/immutable/nodes/7.9c43da7b.js",
  a + "/_app/immutable/nodes/8.e16599ec.js",
  a + "/_app/immutable/nodes/9.d00a5947.js",
  a + "/_app/immutable/assets/404.3df25504.avif",
  a + "/_app/immutable/chunks/i18n-svelte.ca11c0aa.js",
  a + "/_app/immutable/assets/avatar.9d2117a3.png",
  a + "/_app/immutable/assets/avatar.f6a08045.avif",
  a + "/_app/immutable/assets/avatar.ec2b368f.webp",
  a + "/_app/immutable/assets/avatar.3288fe50.jpeg",
  a + "/_app/immutable/assets/avatar.2149bba4.jpeg",
  a + "/_app/immutable/assets/avatar.fa6b069e.jpeg",
  a + "/_app/immutable/assets/avatar.df189fa7.jpeg",
  a + "/_app/immutable/assets/qwer.77ae3ceb.webp",
  a + "/_app/immutable/chunks/image_banner.d6e8d4c2.js",
  a + "/_app/immutable/assets/404.936a22c6.avif",
  a + "/_app/immutable/assets/avatar.d57963db.avif",
  a + "/_app/immutable/assets/avatar.79e8785a.avif",
  a + "/_app/immutable/assets/default_og_card.a8bc64fd.avif",
  a + "/_app/immutable/assets/default_og_card.2ba34cd0.avif",
  a + "/_app/immutable/assets/default_og_card.df8c7476.webp",
  a + "/_app/immutable/assets/default_og_card.1af589c5.avif",
  a + "/_app/immutable/assets/mobile-preview.a8c1e739.avif",
  a + "/_app/immutable/assets/mobile-preview.daf3b20a.avif",
  a + "/_app/immutable/assets/mobile-preview.67d10d03.png",
  a + "/_app/immutable/assets/mobile-preview.5858460a.avif",
  a + "/_app/immutable/assets/mobile-preview.fd25f5cb.avif",
  a + "/_app/immutable/assets/mobile-preview.1af96eba.avif",
  a + "/_app/immutable/assets/mobile-preview.775bf4d7.webp",
  a + "/_app/immutable/assets/mobile-preview.6556ff30.avif",
  a + "/_app/immutable/assets/preview.0a10566d.avif",
  a + "/_app/immutable/assets/preview.bf7f6504.avif",
  a + "/_app/immutable/assets/preview.d1b275c8.png",
  a + "/_app/immutable/assets/preview.62b4c005.avif",
  a + "/_app/immutable/assets/preview.efd40b1d.avif",
  a + "/_app/immutable/assets/preview.6e87c3db.avif",
  a + "/_app/immutable/assets/preview.08386647.webp",
  a + "/_app/immutable/assets/preview.910c0f84.avif",
  a + "/_app/immutable/assets/qwer.80e9876f.avif",
  a + "/_app/immutable/assets/qwer.9e99ba45.avif",
  a + "/_app/immutable/assets/qwer.b1a5b105.avif",
  a + "/_app/immutable/assets/github-mark.7a0dd11e.svg",
  a + "/_app/immutable/assets/cover.e85b808c.avif",
  a + "/_app/immutable/assets/cover.7f46c7d8.avif",
  a + "/_app/immutable/assets/cover.a089909a.jpg",
  a + "/_app/immutable/assets/cover.a1fa4691.avif",
  a + "/_app/immutable/assets/lo-spettacolo.42da9379.avif",
  a + "/_app/immutable/assets/lo-spettacolo.507086b0.avif",
  a + "/_app/immutable/assets/lo-spettacolo.081abe16.jpg",
  a + "/_app/immutable/assets/lo-spettacolo.bab87189.avif",
  a + "/_app/immutable/assets/cover.4fcd2578.avif",
  a + "/_app/immutable/assets/cover.a168a744.jpg",
  a + "/_app/immutable/assets/cover.52517aa8.avif",
  a + "/_app/immutable/assets/cover.b4fc77ae.avif",
  a + "/_app/immutable/assets/cover.58ea9ec8.jpg",
  a + "/_app/immutable/assets/foto-di-classe.17c4adbe.avif",
  a + "/_app/immutable/assets/foto-di-classe.c31750e1.avif",
  a + "/_app/immutable/assets/foto-di-classe.6cb39bca.jpg",
  a + "/_app/immutable/assets/foto-di-classe.3eea2a1c.avif",
  a + "/_app/immutable/assets/cover.d4ee6f34.avif",
  a + "/_app/immutable/assets/cover.a02172b4.avif",
  a + "/_app/immutable/assets/cover.016a81af.jpg",
  a + "/_app/immutable/assets/cover.e72ac826.avif",
  a + "/_app/immutable/assets/cover.ec429b31.avif",
  a + "/_app/immutable/assets/cover.3098b646.avif",
  a + "/_app/immutable/assets/cover.9cdae5b7.jpg",
  a + "/_app/immutable/assets/cover.ff6ac9a5.avif",
  a + "/_app/immutable/assets/cover.a4e065ee.avif",
  a + "/_app/immutable/assets/cover.0fc62875.avif",
  a + "/_app/immutable/assets/cover.7730e669.jpg",
  a + "/_app/immutable/assets/cover.3bb55a3b.avif",
  a + "/_app/immutable/chunks/image_zoom.e37ae301.js",
  a + "/_app/immutable/chunks/index.f3b46ba6.js",
  a + "/_app/immutable/chunks/post.8a24cbd1.js",
  a + "/_app/immutable/assets/post.20994fb9.css",
  a + "/_app/immutable/assets/KaTeX_AMS-Regular.0cdd387c.woff2",
  a + "/_app/immutable/assets/KaTeX_AMS-Regular.30da91e8.woff",
  a + "/_app/immutable/assets/KaTeX_AMS-Regular.68534840.ttf",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Bold.de7701e4.woff2",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Bold.1ae6bd74.woff",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Bold.07d8e303.ttf",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Regular.5d53e70a.woff2",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Regular.3398dd02.woff",
  a + "/_app/immutable/assets/KaTeX_Caligraphic-Regular.ed0b7437.ttf",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Bold.74444efd.woff2",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Bold.9be7ceb8.woff",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Bold.9163df9c.ttf",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Regular.51814d27.woff2",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Regular.5e28753b.woff",
  a + "/_app/immutable/assets/KaTeX_Fraktur-Regular.1e6f9579.ttf",
  a + "/_app/immutable/assets/KaTeX_Main-Bold.0f60d1b8.woff2",
  a + "/_app/immutable/assets/KaTeX_Main-Bold.c76c5d69.woff",
  a + "/_app/immutable/assets/KaTeX_Main-Bold.138ac28d.ttf",
  a + "/_app/immutable/assets/KaTeX_Main-BoldItalic.99cd42a3.woff2",
  a + "/_app/immutable/assets/KaTeX_Main-BoldItalic.a6f7ec0d.woff",
  a + "/_app/immutable/assets/KaTeX_Main-BoldItalic.70ee1f64.ttf",
  a + "/_app/immutable/assets/KaTeX_Main-Italic.97479ca6.woff2",
  a + "/_app/immutable/assets/KaTeX_Main-Italic.f1d6ef86.woff",
  a + "/_app/immutable/assets/KaTeX_Main-Italic.0d85ae7c.ttf",
  a + "/_app/immutable/assets/KaTeX_Main-Regular.c2342cd8.woff2",
  a + "/_app/immutable/assets/KaTeX_Main-Regular.c6368d87.woff",
  a + "/_app/immutable/assets/KaTeX_Main-Regular.d0332f52.ttf",
  a + "/_app/immutable/assets/KaTeX_Math-BoldItalic.dc47344d.woff2",
  a + "/_app/immutable/assets/KaTeX_Math-BoldItalic.850c0af5.woff",
  a + "/_app/immutable/assets/KaTeX_Math-BoldItalic.f9377ab0.ttf",
  a + "/_app/immutable/assets/KaTeX_Math-Italic.7af58c5e.woff2",
  a + "/_app/immutable/assets/KaTeX_Math-Italic.8a8d2445.woff",
  a + "/_app/immutable/assets/KaTeX_Math-Italic.08ce98e5.ttf",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Bold.e99ae511.woff2",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Bold.ece03cfd.woff",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Bold.1ece03f7.ttf",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Italic.00b26ac8.woff2",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Italic.91ee6750.woff",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Italic.3931dd81.ttf",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Regular.68e8c73e.woff2",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Regular.11e4dc8a.woff",
  a + "/_app/immutable/assets/KaTeX_SansSerif-Regular.f36ea897.ttf",
  a + "/_app/immutable/assets/KaTeX_Script-Regular.036d4e95.woff2",
  a + "/_app/immutable/assets/KaTeX_Script-Regular.d96cdf2b.woff",
  a + "/_app/immutable/assets/KaTeX_Script-Regular.1c67f068.ttf",
  a + "/_app/immutable/assets/KaTeX_Size1-Regular.6b47c401.woff2",
  a + "/_app/immutable/assets/KaTeX_Size1-Regular.c943cc98.woff",
  a + "/_app/immutable/assets/KaTeX_Size1-Regular.95b6d2f1.ttf",
  a + "/_app/immutable/assets/KaTeX_Size2-Regular.d04c5421.woff2",
  a + "/_app/immutable/assets/KaTeX_Size2-Regular.2014c523.woff",
  a + "/_app/immutable/assets/KaTeX_Size2-Regular.a6b2099f.ttf",
  a + "/_app/immutable/assets/KaTeX_Size3-Regular.6ab6b62e.woff",
  a + "/_app/immutable/assets/KaTeX_Size3-Regular.500e04d5.ttf",
  a + "/_app/immutable/assets/KaTeX_Size4-Regular.a4af7d41.woff2",
  a + "/_app/immutable/assets/KaTeX_Size4-Regular.99f9c675.woff",
  a + "/_app/immutable/assets/KaTeX_Size4-Regular.c647367d.ttf",
  a + "/_app/immutable/assets/KaTeX_Typewriter-Regular.71d517d6.woff2",
  a + "/_app/immutable/assets/KaTeX_Typewriter-Regular.e14fed02.woff",
  a + "/_app/immutable/assets/KaTeX_Typewriter-Regular.f01f3e87.ttf",
  a + "/_app/immutable/chunks/powerpoint.55759a57.js",
  a + "/_app/immutable/assets/powerpoint.8b541c7d.css",
  a + "/_app/immutable/chunks/scheduler.e99bcb8c.js",
  a + "/_app/immutable/chunks/singletons.835a3787.js",
  a + "/_app/immutable/chunks/timeFormat.ae5793e9.js",
  a + "/_app/immutable/chunks/tippy.1a626561.js",
  a + "/_app/immutable/assets/tippy.7df0e90e.css",
  a + "/_app/immutable/chunks/youtube.624f9842.js",
  a + "/_app/immutable/entry/start.e5fec85e.js"
], u = [
  a + "/about/monkey.mp4",
  a + "/favicon.ico",
  a + "/favicon.png",
  a + "/robots.txt",
  a + "/violenza-di-genere/million-dollar-baby.pdf",
  a + "/~partytown/debug/partytown-atomics.js",
  a + "/~partytown/debug/partytown-media.js",
  a + "/~partytown/debug/partytown-sandbox-sw.js",
  a + "/~partytown/debug/partytown-sw.js",
  a + "/~partytown/debug/partytown-ww-atomics.js",
  a + "/~partytown/debug/partytown-ww-sw.js",
  a + "/~partytown/debug/partytown.js",
  a + "/~partytown/partytown-atomics.js",
  a + "/~partytown/partytown-media.js",
  a + "/~partytown/partytown-sw.js",
  a + "/~partytown/partytown.js"
], _ = [
  a + "/",
  a + "/about",
  a + "/atom.xml",
  a + "/carcere-territorio",
  a + "/feed.json",
  a + "/manifest.webmanifest",
  a + "/pena-di-morte",
  a + "/sitemap.xml",
  a + "/storia-della-mafia",
  a + "/storia-di-informatica",
  a + "/versions.json",
  a + "/violenza-di-genere",
  a + "/web-technologies"
], l = "1709837673095", p = self, f = `cache${l}`, b = o.concat(u).concat(_), r = new Set(b);
p.addEventListener("install", (e) => {
  e.waitUntil(
    caches.open(f).then((s) => s.addAll(b)).then(() => {
      p.skipWaiting();
    })
  );
});
p.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys().then(async (s) => {
      for (const t of s)
        t !== f && await caches.delete(t);
      p.clients.claim();
    })
  );
});
async function n(e) {
  const s = await caches.open(`offline${l}`);
  try {
    const t = await fetch(e);
    return s.put(e, t.clone()), t;
  } catch (t) {
    const i = await s.match(e);
    if (i)
      return i;
    throw t;
  }
}
p.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET" || e.request.headers.has("range"))
    return;
  const s = new URL(e.request.url), t = s.protocol.startsWith("http"), i = s.hostname === self.location.hostname && s.port !== self.location.port, m = s.host === self.location.host && r.has(s.pathname), c = e.request.cache === "only-if-cached" && !m;
  t && !i && !c && e.respondWith(
    (async () => m && await caches.match(e.request) || n(e.request))()
  );
});
